# Generated by Django 5.2.12 on 2026-04-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_name_en_category_name_ru_category_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='online_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Online URL (YouTube, Vimeo, etc.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('article', 'Article'), ('file', 'File'), ('homework', 'Homework')], max_length=50, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
