# Generated by Django 5.2.12 on 2026-04-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_course_teacher_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.country'),
        ),
    ]
